
on: workflow_dispatch
name: Wheel Builder


permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m pip install -U -e . setuptools wheel twine macholib

      - name: Build Wheels
        run: |
          python setup.py sdist bdist_wheels
          python -m twine check dist/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/*
